apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: config
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  # JWT_SECRET: base64 encoded JWT secret
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWhlcmU=
  # API_KEY_STORE: base64 encoded API key configuration
  API_KEY_STORE: e30=  # empty JSON object
  # TLS_CERT: base64 encoded TLS certificate (if using HTTPS)
  # TLS_KEY: base64 encoded TLS private key (if using HTTPS)
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-tls
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  # Generate with: kubectl create secret tls api-gateway-tls --cert=path/to/tls.crt --key=path/to/tls.key
  tls.crt: ""
  tls.key: ""